feat: Add vswitch module (#71)
* feat: Add vswitch module

* refactor(hrobot): Add optional arg for different status codes

* doc(v_switch): Clarify params description

* fix(hrobot): Python 2.6 doesn't support dict comprehension

* fix(v_switch): Print error message for Python 2.x without `u'`

* fix(v_switch): Allow `None` value in servers

This changes allow to don't manage servers if you don't define them.

* fix(v_switch): Minor style changes and use `to_native`

* fix(v_switch): Handle INVALID_INPUT error msg in `add_servers`

* doc(v_switch): Replace pythonic comment

* fix(v_switch): Add ipv6 to calculate diffs

* feat(v_switch): Add support for check mode

* refactor(v_switch): Remove duplicate conditional

* doc(v_switch): Add explicit comment about how to remove servers

* docs(v_switch): Fix minor details

* revert: Minor doc details

Failed with:
```
ERROR: Found 1 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/v_switch.py:0:0: return-syntax-error: RETURN.v_switch.contains.server.contains.status.choices: extra keys not allowed @ data['v_switch']['contains']['server']['contains']['status']['choices']. Got ['ready', 'in process', 'failed']
```

* Revert "revert: Minor doc details"

This reverts commit f9c8d845a3e5e59e892181dd0c597c0eb4195a21.

* Add ignore.txt entries.

* Ok, 2.9 does not need that ignore.

Co-authored-by: Felix Fontein <felix@fontein.de>